### ISSUE TITLE
eph.py stop when the message not all received

### ISSUE THREAD

**Issue by taroyutao** [Azure/azure-event-hubs-python#29]
when i use eph.py 

    # Event loop and host
    LOOP = asyncio.get_event_loop()

    HOST = EventProcessorHost(EventProcessor, EH_CONFIG, STORAGE_MANAGER,
                              ep_params=["param1", "param2"])

    STORAGE_MANAGER.storage_client = BlockBlobService(account_name=STORAGE_ACCOUNT_NAME,
                                                      account_key=STORAGE_KEY,
                                                      request_session=STORAGE_MANAGER.request_session,
                                                      endpoint_suffix="core.chinacloudapi.cn")

    LOOP.run_until_complete(HOST.open_async())
    LOOP.run_until_complete(HOST.close_async())

finally:
    LOOP.stop()

At first, the message can be received normally, but the program will end after a while, the actual message is not read, and then restart program continues to read but all cannot reed all the rest of the message. I use C# EPH method, it works ok.

The support for the Chinese Azure version is not very friendly, future versions hope to improve.

**Comment by taroyutao** [comment]
error info:
[<azure.eventhub.EventData object at 0x0000018EC4955828>, <azure.eventhub.EventData object at 0x0000018EC4965D30>, <azure.eventhub.EventData object at 0x0000018EC370FDA0>, <azure.eventhub.EventData object at 0x0000018EC370FCF8>, <azure.eventhub.EventData object at 0x0000018EC370F1D0>, <azure.eventhub.EventData object at 0x0000018EC492D438>, <azure.eventhub.EventData object at 0x0000018EC492D898>, <azure.eventhub.EventData object at 0x0000018EC492D550>, <azure.eventhub.EventData object at 0x0000018EC492D780>, <azure.eventhub.EventData object at 0x0000018EC492DB38>]
ERROR:azure.eventprocessorhost.partition_pump:4e274000-d01c-4ac3-8adb-6dae8372a75f 0 TypeError("Can't convert 'int' object to str implicitly",)
Traceback (most recent call last):
  File "C:\Users\yuvmtest\PycharmProjects\AzureDemo\venv\lib\site-packages\azure\eventprocessorhost\partition_manager.py", line 80, in run_async
    await self.remove_all_pumps_async("Shutdown")
  File "C:\Users\yuvmtest\PycharmProjects\AzureDemo\venv\lib\site-packages\azure\eventprocessorhost\partition_manager.py", line 248, in remove_all_pumps_async
    await asyncio.gather(*pump_tasks)
  File "C:\Users\yuvmtest\AppData\Local\Programs\Python\Python35\lib\asyncio\futures.py", line 385, in __iter__
    yield self  # This tells Task to wait for completion.
  File "C:\Users\yuvmtest\AppData\Local\Programs\Python\Python35\lib\asyncio\tasks.py", line 288, in _wakeup
Reason: Shutdown
context.partition_id: 0
context.offset: 125832
TypeError("Can't convert 'int' object to str implicitly",)
    value = future.result()
  File "C:\Users\yuvmtest\AppData\Local\Programs\Python\Python35\lib\asyncio\futures.py", line 274, in result
    raise self._exception
  File "C:\Users\yuvmtest\AppData\Local\Programs\Python\Python35\lib\asyncio\tasks.py", line 239, in _step
    result = coro.send(value)
  File "C:\Users\yuvmtest\PycharmProjects\AzureDemo\venv\lib\site-packages\azure\eventprocessorhost\partition_manager.py", line 230, in remove_pump_async
    await captured_pump.close_async(reason)
  File "C:\Users\yuvmtest\PycharmProjects\AzureDemo\venv\lib\site-packages\azure\eventprocessorhost\partition_pump.py", line 108, in close_async
    raise err
  File "C:\Users\yuvmtest\PycharmProjects\AzureDemo\venv\lib\site-packages\azure\eventprocessorhost\partition_pump.py", line 101, in close_async
    await self.processor.close_async(self.partition_context, reason)
  File "C:/Users/yuvmtest/PycharmProjects/AzureDemo/EventHub/EpochReceiver.py", line 48, in close_async
    print("context.sequence_number: " + context.sequence_number)
TypeError: Can't convert 'int' object to str implicitly

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:/Users/yuvmtest/PycharmProjects/AzureDemo/EventHub/EpochReceiver.py", line 125, in <module>
    LOOP.run_until_complete(HOST.close_async())
  File "C:\Users\yuvmtest\AppData\Local\Programs\Python\Python35\lib\asyncio\base_events.py", line 342, in run_until_complete
    return future.result()
  File "C:\Users\yuvmtest\AppData\Local\Programs\Python\Python35\lib\asyncio\futures.py", line 274, in result
    raise self._exception
  File "C:\Users\yuvmtest\AppData\Local\Programs\Python\Python35\lib\asyncio\tasks.py", line 237, in _step
    result = coro.throw(exc)
  File "C:\Users\yuvmtest\PycharmProjects\AzureDemo\venv\lib\site-packages\azure\eventprocessorhost\eph.py", line 59, in close_async
    await self.partition_manager.stop_async()
  File "C:\Users\yuvmtest\PycharmProjects\AzureDemo\venv\lib\site-packages\azure\eventprocessorhost\partition_manager.py", line 67, in stop_async
    await self.run_task
  File "C:\Users\yuvmtest\AppData\Local\Programs\Python\Python35\lib\asyncio\futures.py", line 385, in __iter__
    yield self  # This tells Task to wait for completion.
  File "C:\Users\yuvmtest\AppData\Local\Programs\Python\Python35\lib\asyncio\tasks.py", line 288, in _wakeup
    value = future.result()
  File "C:\Users\yuvmtest\AppData\Local\Programs\Python\Python35\lib\asyncio\futures.py", line 274, in result
    raise self._exception
  File "C:\Users\yuvmtest\AppData\Local\Programs\Python\Python35\lib\asyncio\tasks.py", line 237, in _step
    result = coro.throw(exc)
  File "C:\Users\yuvmtest\PycharmProjects\AzureDemo\venv\lib\site-packages\azure\eventprocessorhost\partition_manager.py", line 82, in run_async
    raise Exception("Failed to remove all pumps {!r}".format(err))
Exception: Failed to remove all pumps TypeError("Can't convert 'int' object to str implicitly",)
ERROR:asyncio:Task was destroyed but it is pending!
task: <Task pending coro=<PartitionReceiver.run() running at C:\Users\yuvmtest\PycharmProjects\AzureDemo\venv\lib\site-packages\azure\eventprocessorhost\eh_partition_pump.py:132> wait_for=<Future pending cb=[wrap_future.<locals>._check_cancel_other() at C:\Users\yuvmtest\AppData\Local\Programs\Python\Python35\lib\asyncio\futures.py:403, Task._wakeup()]> cb=[Task._wakeup()]>
ERROR:uamqp.c_uamqp:b'Failure: sending socket failed 10038.' (b'./src/vendor/azure-uamqp-c/deps/azure-c-shared-utility/adapters/socketio_win32.c':b'socketio_send':422)
ERROR:uamqp.c_uamqp:b'xio_send failed' (b'./src/vendor/azure-uamqp-c/deps/azure-c-shared-utility/src/tlsio_schannel.c':b'send_chunk':484)
ERROR:uamqp.c_uamqp:b'send_chunk failed' (b'./src/vendor/azure-uamqp-c/deps/azure-c-shared-utility/src/tlsio_schannel.c':b'internal_send':525)
ERROR:uamqp.c_uamqp:b'send failed' (b'./src/vendor/azure-uamqp-c/deps/azure-c-shared-utility/src/tlsio_schannel.c':b'tlsio_schannel_send':1273)
ERROR:uamqp.c_uamqp:b'xio_send failed' (b'./src/vendor/azure-uamqp-c/src/saslclientio.c':b'saslclientio_send_async':1182)
ERROR:uamqp.c_uamqp:b'Cannot send encoded bytes' (b'./src/vendor/azure-uamqp-c/src/connection.c':b'on_bytes_encoded':255)
ERROR:uamqp.c_uamqp:b'link detach failed' (b'./src/vendor/azure-uamqp-c/src/message_receiver.c':b'messagereceiver_close':401)

**Comment by annatisch** [comment]
@taroyutao - Thanks! I will take a look.

When you say "support for the Chinese Azure version is not very friendly" - could you give me more details on what I can improve here?

**Comment by annatisch** [comment]
@taroyutao,

Just to clarify - from the error message, it looks like you're running the new EPH from the develop branch, however the eph.py script looks like the one from the master branch. Are you running this one here?
https://github.com/Azure/azure-event-hubs-python/blob/develop/examples/eph.py

Thanks

**Comment by taroyutao** [comment]
Sorry for response too later.

the EventHubCobfig() method only support Global Azure:

` 
   def __init__(self, sb_name, eh_name, policy, sas_key, consumer_group):
        self.sb_name = sb_name
        self.eh_name = eh_name
        self.policy = policy
        self.sas_key = sas_key
        self.consumer_group = consumer_group
        self.client_address = self.get_client_address()
        self.rest_token = self.get_rest_token()
`

if we want use it to china Azure , we have to use client_address:

`
    ADDRESS = ("amqps://"
               "RootManageSharedAccessKey"
               ":"
               "wnwcU%2bVjKLGgNUwiecwAyHb9gAVPDIC%2bRvXu2JcDINc%3d"
               "@"
               "cznamespace.servicebus.chinacloudapi.cn"
               "/"
               "yutaoeventhubtest")

    EH_CONFIG.client_address = ADDRESS
`
I think you can add one parameter such as:
servicebus_prefix = ".servicebus.chinacloudapi.cn"

**Comment by taroyutao** [comment]
my running code：

import asyncio
from azure.eventprocessorhost import AbstractEventProcessor
from azure.eventprocessorhost import AzureStorageCheckpointLeaseManager
from azure.eventprocessorhost import EventHubConfig
from azure.eventprocessorhost import EventProcessorHost
from azure.storage.blob import BlockBlobService


class EventProcessor(AbstractEventProcessor):


    """
    Example Implmentation of AbstractEventProcessor
    """
    def __init__(self, params=None):
        """
        Init Event processor
        """
        self._msg_counter = 0
    async def open_async(self, context):
        """
        Called by processor host to initialize the event processor.
        """
        # logging.info("Connection established %s", context.partition_id)
        print(context.partition_id)
        self._msg_counter = self._msg_counter + 1
        print(self._msg_counter)

    async def close_async(self, context, reason):
        """
        Called by processor host to indicate that the event processor is being stopped.
        (Params) Context:Information about the partition
        """
        # logging.info("Connection closed (reason %s, id %s, offset %s, sq_number %s)", reason,
        #              context.partition_id, context.offset, context.sequence_number)

        print("Reason: " + reason)
        print("context.partition_id: " + context.partition_id)
        print("context.offset: " + context.offset)
        print("context.sequence_number: " + context.sequence_number)

    async def process_events_async(self, context, messages):
        """
        Called by the processor host when a batch of events has arrived.
        This is where the real work of the event processor is done.
        (Params) Context: Information about the partition, Messages: The events to be processed.
        """
        # logging.info("Events processed %s %s", context.partition_id, messages)
        print(context.partition_id)
        print(messages)
        print("-----")
        await context.checkpoint_async()

    async def process_error_async(self, context, error):
        """
        Called when the underlying client experiences an error while receiving.
        EventProcessorHost will take care of recovering from the error and
        continuing to pump messages,so no action is required from
        (Params) Context: Information about the partition, Error: The error that occured.
        """
        print(repr(error))
        # print()
        # logging.error("Event Processor Error %s ", repr(error))

try:

    # Storage Account Credentials
    STORAGE_ACCOUNT_NAME = "yuvmtestdiag489"
    STORAGE_KEY = "***************************************"
    LEASE_CONTAINER_NAME = "leases8"

    # Eventhub config and storage manager
    EH_CONFIG = EventHubConfig('cznamespace', 'yutaoeventhubtest','RootManageSharedAccessKey',
                               '*************************************', consumer_group="$default")

    EventHubConfig.sb_name = "cznamespace"
    EventHubConfig.eh_name = "yutaoeventhubtest"
    EventHubConfig.policy = "RootManageSharedAccessKey"
    EventHubConfig.sas_key = "****************************"
    EventHubConfig.consumer_group = "$default"

    ADDRESS = ("amqps://"
               "RootManageSharedAccessKey"
               ":"
               "***********************************"
               "@"
               "cznamespace.servicebus.chinacloudapi.cn"
               "/"
               "yutaoeventhubtest")

    EH_CONFIG.client_address = ADDRESS


    STORAGE_MANAGER = AzureStorageCheckpointLeaseManager(STORAGE_ACCOUNT_NAME, STORAGE_KEY,
                                                         LEASE_CONTAINER_NAME, storage_blob_prefix = "blob.core.chinacloudapi.cn")


    #Event loop and host
    LOOP = asyncio.get_event_loop()
    HOST = EventProcessorHost(EventProcessor, EH_CONFIG, STORAGE_MANAGER,
                              ep_params=["param1", "param2"], loop=LOOP)

    STORAGE_MANAGER.storage_client = BlockBlobService(account_name=STORAGE_ACCOUNT_NAME,
                                                      account_key=STORAGE_KEY,
                                                      request_session=STORAGE_MANAGER.request_session,
                                                      endpoint_suffix="core.chinacloudapi.cn")


    LOOP.run_until_complete(HOST.open_async())
    LOOP.run_until_complete(HOST.close_async())

finally:
    
    LOOP.stop()

**Comment by taroyutao** [comment]
Looking forward to your reply.

Thanks

**Comment by taroyutao** [comment]
Dear @annatisch ,

Thanks.

I hava notice the cause of the reason,

TypeError("Can't convert 'int' object to str implicitly",)

and I replaced your code:
print("context.sequence_number: {}".format(context.sequence_number))

the error inforamtion will disapper, the progress also will Shutdown but not all the message received.

when I restart the progress and continue to receive the message, The same situation will happen again.

I restart the progress several time and all the messages will be received. 

I think the receiving action should finished at one time not several times.

**The first running:**

Reason: Shutdown
context.partition_id: 0
context.offset: 126840
context.sequence_number: 2299
Reason: Shutdown
context.partition_id: 1
context.offset: 126280
context.sequence_number: 2289

Process finished with exit code 0

**the second running:**

Reason: Shutdown
context.partition_id: 0
context.offset: 245720
context.sequence_number: 4429
Reason: Shutdown
context.partition_id: 1
context.offset: 244040
context.sequence_number: 4399

Process finished with exit code 0

**the third running:**

Reason: Shutdown
context.partition_id: 0
context.offset: 382120
context.sequence_number: 6879

Process finished with exit code 0


**the fouth running:**

Reason: Shutdown
context.partition_id: 1
context.offset: 363208
context.sequence_number: 6539
0
[<azure.eventhub.EventData object at 0x000001D426EA7748>, <azure.eventhub.EventData object at 0x000001D426EA7278>, <azure.eventhub.EventData object at 0x000001D426E97470>, <azure.eventhub.EventData object at 0x000001D426E97710>, <azure.eventhub.EventData object at 0x000001D426E979B0>]
-----
Reason: Shutdown
context.partition_id: 0
context.offset: 445120
context.sequence_number: 8004

Process finished with exit code 0

**the fifth running:**

Reason: Shutdown
context.partition_id: 0
context.offset: 445120
context.sequence_number: 8004
1
[<azure.eventhub.EventData object at 0x000001CE7D2F7C50>, <azure.eventhub.EventData object at 0x000001CE7D2F7390>, <azure.eventhub.EventData object at 0x000001CE7D2F7630>, <azure.eventhub.EventData object at 0x000001CE7D2F7F60>, <azure.eventhub.EventData object at 0x000001CE7D2F7898>]
-----
Reason: Shutdown
context.partition_id: 1
context.offset: 445120
context.sequence_number: 8004

Process finished with exit code 0

From the offset and sequence_number we know that all the messages were received.

the servicebus exployer info:
![partitioninfo](https://user-images.githubusercontent.com/20704268/40153202-3385ccda-59bb-11e8-941e-2886a5b44ce7.png)

When I used java or C# sdk with eph, the messages can been received at one time.

**Comment by annatisch** [comment]
Thanks @taroyutao - I think this is because of the close_async being called straight away:
```
LOOP.run_until_complete(HOST.open_async())
LOOP.run_until_complete(HOST.close_async())
```
This will start the EPH, then close it down again - which is okay for a sample, but not overly useful in a real-world scenario.
If you remove the close_async call, or replace it with something that will shut down after a certain length of time or certain number of messages received then it should run for longer.

**Comment by annatisch** [comment]
For example - the updated sample in the develop branch uses a call that waits for 2 minutes then shuts down the EPH:
```
async def wait_and_close(host):
    """
    Run EventProcessorHost for 2 minutes then shutdown.
    """
    await asyncio.sleep(120)
    await host.close_async()


try:
    loop = asyncio.get_event_loop()

    # Storage Account Credentials
    STORAGE_ACCOUNT_NAME = os.environ.get('AZURE_STORAGE_ACCOUNT')
    STORAGE_KEY = os.environ.get('AZURE_STORAGE_ACCESS_KEY')
    LEASE_CONTAINER_NAME = "leases"

    NAMESPACE = os.environ.get('EVENT_HUB_NAMESPACE')
    EVENTHUB = os.environ.get('EVENT_HUB_NAME')
    USER = os.environ.get('EVENT_HUB_SAS_POLICY')
    KEY = os.environ.get('EVENT_HUB_SAS_KEY')

    # Eventhub config and storage manager 
    eh_config = EventHubConfig(NAMESPACE, EVENTHUB, USER, KEY, consumer_group="$default")
    eh_options = EPHOptions()
    eh_options.release_pump_on_timeout = True
    eh_options.debug_trace = False
    storage_manager = AzureStorageCheckpointLeaseManager(
        STORAGE_ACCOUNT_NAME, STORAGE_KEY, LEASE_CONTAINER_NAME)

    # Event loop and host
    host = EventProcessorHost(
        EventProcessor,
        eh_config,
        storage_manager,
        ep_params=["param1","param2"],
        eph_options=eh_options,
        loop=loop)

    tasks = asyncio.gather(
        host.open_async(),
        wait_and_close(host))
    loop.run_until_complete(tasks)

except KeyboardInterrupt:
    # Canceling pending tasks and stopping the loop
    for task in asyncio.Task.all_tasks():
        task.cancel()
    loop.run_forever()
    tasks.exception()

finally:
    loop.stop()
```
