### ISSUE TITLE
Getting: Send failed: CBS Authentication Expired. Error

### ISSUE THREAD

**Issue by v-sinitsa** [Azure/azure-event-hubs-python#89]
This error seems to show up after ive been running my client for about a day. The thing is im running 7 different clients at the same time in k8s and it seems to only happen on one client and all the other clients are fine.

**Comment by MingxuanLi** [comment]
Same issue here, wonder why this is happening ?

**Comment by v-sinitsa** [comment]
IDK but I ended up switching back to the http client instead. It seems to be more stable.

**Comment by annatisch** [comment]
Thanks @v-sinitsa  and @MingxuanLi,
Sorry for the delay!

Are you able to give me details of the error? It would be great to see a stack trace of some kind.
Just to confirm - is this only happening for a Sender? 
Or are you seeing similar behaviour for receiving as well?

Thanks for the report!! :)

**Comment by smhoang** [comment]
Same issue with me, and it happened when I run eventhub client for a haft day or so. Exception: 'Send failed: CBS Authentication Expired.'

**Comment by annatisch** [comment]
Thanks @smhoang!
Are you able to provide any code snippets to show how you're using the sender?
Additionally are the any further error details in your logs?

**Comment by smhoang** [comment]
Hi @annatisch , please find the code snippets and stack traces below:
`                client = EventHubClient.from_connection_string(conn_str)
                sender = client.add_sender(partition="0")
                client.run()
                sender.send(EventData(json.dumps(msg_dict)))
`
After 7hours running:
`Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/azure/eventhub/sender.py", line 206, in send
    self._handler.send_message(event_data.message)
  File "/usr/local/lib/python3.6/dist-packages/uamqp/client.py", line 694, in send_message
    running = self.do_work()
  File "/usr/local/lib/python3.6/dist-packages/uamqp/client.py", line 377, in do_work
    if not self.client_ready():
  File "/usr/local/lib/python3.6/dist-packages/uamqp/client.py", line 359, in client_ready
    if not self.auth_complete():
  File "/usr/local/lib/python3.6/dist-packages/uamqp/client.py", line 340, in auth_complete
    timeout, auth_in_progress = self._auth.handle_token()
  File "/usr/local/lib/python3.6/dist-packages/uamqp/authentication/cbs_auth.py", line 130, in handle_token
    raise errors.TokenExpired("CBS Authentication Expired.")
uamqp.errors.TokenExpired: CBS Authentication Expired.`

**Comment by jublair** [comment]
I've been experiencing the same error for receiving events on Azure Databricks. 

<command-3139291654564850> in <module>()
     11   print("Client connected to feed {}, partition {} - listening for new entries".format(feed, recv_no))
     12   while True:
---> 13     receivedata(receiver, feed, tablename, debug)
     14 except Exception as ex:
     15   ex_func = ex

<command-3792056478023537> in receivedata(receiver, feed, tablename, debug)
     13 
     14 def receivedata(receiver, feed, tablename, debug=False):
---> 15   batch = receiver.receive(timeout=5000)
     16   if not batch: return
     17 

/databricks/python/lib/python3.5/site-packages/azure/eventhub/receiver.py in receive(self, max_batch_size, timeout)
    259             error = EventHubError("Receive failed: {}".format(e))
    260             self.close(exception=error)
--> 261             raise error

EventHubError: Receive failed: CBS Authentication Expired.

**Comment by annatisch** [comment]
Thanks @jublair! When you say "1-2 hours"...
The first token refresh should happen around 50 minutes in. If this fails it will likely raise an error at that point, otherwise the token will expire at about 1 hour 10 minutes.
The second token refresh should occur around 1 hour 50 minutes.

So in the 1-2 hour time frame, if it stops receiving at 1 hour, or very soon after with an auth error - then it likely never achieved even one successful token refresh. Could you provide specifics on the timing and is the timing always consistent?

**Comment by jublair** [comment]
Hi @annatisch,

Apologies for the lack of clarity! Here are a few of our latest total run-times (noting that there's a few minutes of warm-up before an event hub client is generated) for Databricks jobs which generate this error:

3h 53m 8s
1h 57m 53s
1h 56m 54s
3h 50m 55s
7h 35m 15s

As you noted, and contrary to my original "1-2 hr" claim, these failures appear to fall around the 50 minute mark of any given hour, but can sometimes sustain a run longer than 1-2 hours.

**Comment by annatisch** [comment]
Thanks for your patience everyone - I'm hoping to have a patch to support attempting a reconnect in the case of a TokenExpiration within the next week or so.
