### ISSUE TITLE
Unable to send events to EH : possible connection string issue

### ISSUE THREAD

**Issue by Heenanl** [Azure/azure-event-hubs-python#92]
Unable to start connection to send events to the event hub resource.

send.py:
ADDRESS = "sb://ehrelay42test.servicebus.windows.net/myeventhub"

Error message:
'eventhub.pysdk-35e93ed6': All clients failed to start.
Traceback (most recent call last):
  File "send.py", line 33, in <module>
    client.run()
  File "\lib\site-packages\azure\eventhub\client.py", line 322, in run
    raise failed[0]
azure.eventhub.common.EventHubError: Unable to open authentication session on connection b'EHSender-f0e204dc-2586-4580-af9a-326f05c32063-partition0'.
Please confirm target hostname exists: b'ehrelay42test.servicebus.windows.net'

**Comment by Heenanl** [comment]
Resolved.
The reason was VPN .
The sending worked when i switched it off.
